---
# tasks file for da.dev

- name: Install epel release
  package:
    name:
      - epel-release
    state: latest
    update_cache: true

- name: Install jdk
  yum:
    name:
      - java-11-openjdk-devel-11.0.16.1.1-1.el7_9.x86_64
    state: latest
    update_cache: true

- name: "Get installed packages"
  yum:
    list: "installed"
  register: installed_packages

- name: "Install missing packages"
  package: 
    state: "present"
    name: "{{ item }}"
  with_items: "{{ packages_to_install | difference(installed_packages | json_query('results[*].name')) }}"

