---
# tasks file for da.dev

- name: "Get installed packages"
  yum:
    list: "installed"
  register: installed_packages

- name: "Install missing packages"
  package: 
    state: "present"
    name: "{{ item }}"
  with_items: "{{ packages_to_install | difference(installed_packages | json_query('results[*].name')) }}"
  vars:
      packages_to_install: "{{ lookup('file', '../files/packages').splitlines() }}"

- name: Copy pip requirements file 
  ansible.builtin.copy:
    src: ../files/requirements.txt
    dest: /opt/requirements.txt
    owner: vagrant
    group: vagrant
    mode: '0777'

- name: Install python requirements
  pip:
    requirements: /opt/requirements.txt
    executable: pip3