# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :kvm do |v|
    v.memory = 512
    v.cpus = 1
    v.linked_clone = true
  end

   # gitlab server
  #  config.vm.define "gitlab" do |app|
  #   app.vm.hostname = "gitlab"
  #   app.vm.network :private_network, ip: "192.168.56.4"
  #   app.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../ansible/playbook.yml"
  #   end
  # end

  # # nfs server
  # config.vm.define "nfs" do |app|
  #   app.vm.hostname = "nfs"
  #   app.vm.network :private_network, ip: "192.168.56.5"
  #   app.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../ansible/playbook.yml"
  #   end
  # end

  # # postgres server
  # config.vm.define "postgres" do |app|
  #   app.vm.hostname = "postgres"
  #   app.vm.network :private_network, ip: "192.168.56.6"
  #   app.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../ansible/playbook.yml"
  #   end
  # end

  # da dev server
  config.vm.define "da-dev" do |app|
    app.vm.hostname = "da-dev"
    app.vm.network :private_network, ip: "192.168.56.7"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
    end
  end

  #  # jupyterhub server
  #  config.vm.define "jupyterhub" do |app|
  #   app.vm.hostname = "jupyterhub"
  #   app.vm.network :private_network, ip: "192.168.56.8"
  #   app.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../ansible/playbook.yml"
  #   end
  # end
end
