---
- hosts: gitlab
  gather_facts: yes
  # accelerate: true
  # accelerate_port: 5099 #default port
  become: true
  roles:
    - geerlingguy.gitlab

- hosts: nfs
  gather_facts: yes
  become: true
  roles:
    - geerlingguy.nfs

- hosts: postgres
  gather_facts: yes
  become: true
  roles:
    - geerlingguy.postgresql

- hosts: da-dev
  gather_facts: yes
  become: true
  roles:
    - da.dev