---
- hosts: gitlab
  gather_facts: yes
  # accelerate: true
  # accelerate_port: 5099 #default port
  become: true
  roles:
    - geerlingguy.gitlab
    - geerlingguy.nfs

- hosts: nfs
  gather_facts: yes
  # accelerate: true
  # accelerate_port: 5099 #default port
  become: true
  roles:
    - geerlingguy.nfs